TradeMarketing/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Great Plains Customer Account Number</description>
    <externalId>true</externalId>
    <inlineHelpText>Great Plains Customer Account Number</inlineHelpText>
    <label>Account #</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

GoodTIme_Intelij/src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>SFINV-{00000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TradeMarketing/force-app/main/default/classes/InventoryTriggerHandler.cls
public with sharing class InventoryTriggerHandler {

    public static void validateNewInventory(List<Inventory__c> listInventories){
        Set<Id>accountIds = new Set<Id>();
        Set<Date>inventoryDates = new Set<Date>();
        for (Inventory__c item : listInventories) {
            accountIds.add(item.Account__c);
            inventoryDates.add(item.Visit_Date__c);
        }

        Map<Id,Set<Date>> accountInventoryMap = new Map<Id,Set<Date>>();
        for (Account item : [
                SELECT Id,
                (SELECT Visit_Date__c FROM Inventory__r WHERE Visit_Date__c IN : inventoryDates)
                FROM Account
                WHERE Id IN : accountIds
                ]) {
            if (item.Inventory__r.size() > 0) {
                Set<Date> currentInventoryDates = new Set<Date>();
                for (Inventory__c inventoryItem : item.Inventory__r) {
                    currentInventoryDates.add(inventoryItem.Visit_Date__c);
                }
                accountInventoryMap.put(item.Id, currentInventoryDates);
            }
        }

        for (Inventory__c item : listInventories) {
            if (accountInventoryMap.containsKey(item.account__c)
                && accountInventoryMap.get(item.account__c).contains(item.Visit_Date__c)) {
                item.addError('Inventory for this date already exists');
            }
        }
    }
}