TradeMarketing/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Great Plains Customer Account Number</description>
    <externalId>true</externalId>
    <inlineHelpText>Great Plains Customer Account Number</inlineHelpText>
    <label>Account #</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

TradeMarketing/mdapi-components/unpackaged/objects/Product_Brand__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Product Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of the discount, used to calculate recap form quantities.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Starting date of the TMA, used to calculate the recap quantities.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trade_Marketing_Agreement_Promotion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trade Marketing Agreement Promotion</label>
        <referenceTo>Trade_Marketing_Agreement_Promotion__c</referenceTo>
        <relationshipLabel>Trade Marketing Agreements</relationshipLabel>
        <relationshipName>Trade_Marketing_Agreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Trade Marketing Agreement</label>
    <nameField>
        <label>Trade Marketing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Allowance_Rate__c</fullName>
        <label>Allowance Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Allowance_Rate__c</fullName>
        <description>Maximum allowance rate allowed on this line item.</description>
        <formula>Trade_Marketing_Agreement__r.Trade_Marketing_Agreement_Promotion__r.Maximum_Allowance_Rate__c</formula>
        <label>Maximum Allowance Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Marketing_Agreement__c</fullName>
        <label>Trade Marketing Agreement</label>
        <referenceTo>Trade_Marketing_Agreement__c</referenceTo>
        <relationshipLabel>Trade Marketing Agreement Line Items</relationshipLabel>
        <relationshipName>Trade_Marketing_Agreement_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trade Marketing Agreement Line Item</label>
    <nameField>
        <displayFormat>TMA-{00000000}</displayFormat>
        <label>TMA Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement_Promotion__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Allowance_Rate__c</fullName>
        <description>Maximum Allowance Rate for this promotion. Do not change once created.</description>
        <inlineHelpText>Maximum Allowance Rate for this promotion. Do not change once created.</inlineHelpText>
        <label>Maximum Allowance Rate</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Trade Marketing Agreement Promotion</label>
    <nameField>
        <label>TMA Promotion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreement Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/classes/GT_TMARecapClass_TwoTest.cls
/**
 * Created by christellejoseph on 6/28/20.
 */
@IsTest
public with sharing class GT_TMARecapClass_TwoTest
{

	@IsTest
	public static void testBuildDataTableWithTMAInfo()
	{
		Trade_Marketing_Agreement_Promotion__c tmaPromo = new Trade_Marketing_Agreement_Promotion__c(
				Name = 'Promo',
				Maximum_Allowance_Rate__c = 5
		);

		insert tmaPromo;

		Product_Brand__c brand = new Product_Brand__c(
				Name = 'Cool Brand',
				Description__c = 'some description',
				Trade_Marketing_Agreement_Promotion__c = tmaPromo.Id
		);

		insert brand;

		Account acc = New Account(
				name = 'Account ',
				Account__c  = '1234560'

		);

		insert acc;

		Trade_Marketing_Agreement__c tmAgreement = new Trade_Marketing_Agreement__c(
				Name = 'tmAgreement',
				Account__c = acc.Id,
				Trade_Marketing_Agreement_Promotion__c = tmaPromo.Id,
				Start_Date__c = date.today(),
				End_Date__c = date.today() + 10
		);

		insert tmAgreement;

		List<Trade_Marketing_Agreement_Line_Item__c> tmaList = new List<Trade_Marketing_Agreement_Line_Item__c>();

		Trade_Marketing_Agreement_Line_Item__c tmaLineItem1 = new Trade_Marketing_Agreement_Line_Item__c(
				Trade_Marketing_Agreement__c = tmAgreement.Id,
				Product_Brand__c = brand.Id,
				Allowance_Rate__c = 3,
				Quantity__c = 40,
				Discount__c = 10

				//120
		);

		tmaList.add(tmaLineItem1);

		Trade_Marketing_Agreement_Line_Item__c tmaLineItem2 = new Trade_Marketing_Agreement_Line_Item__c(
				Trade_Marketing_Agreement__c = tmAgreement.Id,
				Product_Brand__c = brand.Id,
				Allowance_Rate__c = 2,
				Quantity__c = 20,
				Discount__c = 5
				//40
		);

		tmaList.add(tmaLineItem2);

		Trade_Marketing_Agreement_Line_Item__c tmaLineItem3 = new Trade_Marketing_Agreement_Line_Item__c(
				Trade_Marketing_Agreement__c = tmAgreement.Id,
				Product_Brand__c = brand.Id,
				Allowance_Rate__c = 3,
				Quantity__c = 0,
				Discount__c = 0
				//270
		);

		tmaList.add(tmaLineItem3);

		insert tmaList;

		Test.startTest();
		PageReference pageRef = page.GT_TMARecapForm_Two;
		pageRef.getParameters().put('id',tmAgreement.Id);
		Test.setCurrentPage(pageRef);
		GT_TMARecapClass_Two controller = new GT_TMARecapClass_Two(new ApexPages.StandardController(tmAgreement));
		controller.displayTMARecapFormDataTable();

		List<Trade_Marketing_Agreement_Line_Item__c> data = [
				SELECT Id, Product_Brand__r.Name, Product_Brand__r.Description__c, Allowance_Rate__c, Quantity__c,
						Discount__c, Trade_Marketing_Agreement__r.Start_Date__c,
						Trade_Marketing_Agreement__r.End_Date__c
				From Trade_Marketing_Agreement_Line_Item__c
		];



		system.assertEquals(3, data.size());
		System.assertEquals(15.00, controller.totalDiscount);

		controller.tmaWrapList.get(2).quantity = 90;

		controller.save();


		List<Trade_Marketing_Agreement_Line_Item__c> data2 = [
				SELECT Id, Product_Brand__r.Name, Product_Brand__r.Description__c, Allowance_Rate__c, Quantity__c,
						Discount__c, Trade_Marketing_Agreement__r.Start_Date__c,
						Trade_Marketing_Agreement__r.End_Date__c
				From Trade_Marketing_Agreement_Line_Item__c
		];


		System.assertEquals(430, controller.totalDiscount);





		Test.stopTest();

	}

}