TradeMarketing/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Great Plains Customer Account Number</description>
    <externalId>true</externalId>
    <inlineHelpText>Great Plains Customer Account Number</inlineHelpText>
    <label>Account #</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

GoodTIme_Intelij/src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>SFINV-{00000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Inventory_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Line Items</relationshipLabel>
        <relationshipName>Inventory_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Inventory Line Items</relationshipLabel>
        <relationshipName>Inventory_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.Item_Status__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <filterItems>
                <field>Product2.Item_Status__c</field>
                <operation>equals</operation>
                <value>2</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Line Items</relationshipLabel>
        <relationshipName>Inventory_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inventory Line Item</label>
    <nameField>
        <displayFormat>ILI-{000000}</displayFormat>
        <label>Inventory Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TradeMarketing/mdapi-components/unpackaged/objects/Product_Brand__c.object
<CustomObject>
    <label>Product Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Retail_Price__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <description>This records the price of the brand family at a retail location.</description>
        <label>Price</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Brand__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Brand that the price is being recorded for</description>
        <label>Product Brand</label>
        <referenceTo>Product_Brand__c</referenceTo>
        <relationshipLabel>Retail Prices</relationshipLabel>
        <relationshipName>Retail_Prices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retail_Price_Archive__c</fullName>
        <label>Retail Price Archive</label>
        <referenceTo>Retail_Price_Archive__c</referenceTo>
        <relationshipLabel>Retail Prices</relationshipLabel>
        <relationshipName>Retail_Prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Retail Price</label>
    <nameField>
        <displayFormat>GTRP{0000000000}</displayFormat>
        <label>Retail Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Retail_Price_Archive__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Retail Price Archives</relationshipLabel>
        <relationshipName>Retail_Price_Archives</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recorded_Date__c</fullName>
        <description>Date that the pricing information was recorded by Area Sales Manager.</description>
        <label>Recorded Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Retail Price Archive</label>
    <nameField>
        <displayFormat>GTRPA{0000000000}</displayFormat>
        <label>Retail Price Archives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retail Price Archives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TradeMarketing/force-app/main/default/classes/GT_PriceTrackingTest.cls
@isTest
public with sharing class GT_PriceTrackingTest {
    public GT_PriceTrackingTest() {

    }
    

    static testmethod void test_AddBrand () { 

        //Create account, inventory, inventory line items, pricebooks, products, and brands
        Account acc = createAccountWithInventories();

        GT_PriceTrackingClass controller1 = new GT_PriceTrackingClass(new ApexPages.StandardController(acc));
	

        //get the brand IDs to add them to the select list 
        List<Product_Brand__c> lst_PBs = [SELECT Id, Name FROM Product_Brand__c];

        Test.startTest();
        
        PageReference pg=Page.GT_PriceTrackingPage;
        pg.getParameters().put('id',acc.Id);
        

        Test.setCurrentPage(pg);
        controller1.getRetailPriceArchives();

        List<Retail_Price_Archive__c> lst_RPAs = [SELECT Id FROM Retail_Price_Archive__c];

        //after the page is loaded and the action is triggered there should be an Retail Price Archive Created 
        system.assertEquals(1, lst_RPAs.size());

        //set the conditions necessary to add a brand - update the list with a checked brand 
        controller1.selectedList = lst_PBs.get(0).Id + ',true,'+ lst_PBs.get(1).Id + ',false,' + lst_PBs.get(2).Id + ',true';

        controller1.addBrand();
        
        //set the wRetailPrice to an arbitraty value so you can save it 
        for(GT_PriceTrackingClass.wRetailPrice wRP : controller1.archivePrices){
            wRP.wrapRP.Price__c = 1;
        }

        //save the brand price 
        controller1.saveChanges();

        //after the brand is added there should be 2 retail prices
        List<Retail_Price__c> lst_RPs = [SELECT Id FROM Retail_Price__c];
        system.assertEquals(2, lst_RPs.size());

        //one brand was not checked as true on the selectedList so it remains on the inventory, but has not been added the RPA use the getInvtoryBrands method to bring it into the list.
        controller1.getInventoryBrands();

        //remove the brand that was added by the import
        controller1.removeBrandName = lst_PBs.get(1).Name;
        controller1.removeBrand();

        //save the brand prices 
        controller1.saveChanges();

        //verify that the brand was removed from the list and not commited to the database 
        lst_RPs = [SELECT Id FROM Retail_Price__c];
        system.assertEquals(2, lst_RPs.size());

        
        //run the import again to verify its functionality 
        controller1.getInventoryBrands();

        //set the wRetailPrice to an arbitraty value so you can save it 
        for(GT_PriceTrackingClass.wRetailPrice wRP : controller1.archivePrices){
            wRP.wrapRP.Price__c = 1;
        }

        //save the brand prices 
        controller1.saveChanges();

        //after the brand is added, the import is run there should be 3 retail prices
        lst_RPs = [SELECT Id FROM Retail_Price__c];
        system.assertEquals(3, lst_RPs.size());

        //delete RP from the list and database
        controller1.deleteItemId = lst_RPs.get(2).Id;
        controller1.createDeletionRequest();

        //verify that RP was deleted from the database
        lst_RPs = [SELECT Id FROM Retail_Price__c];
        system.assertEquals(2, lst_RPs.size());

        //arbitrary code coverage for delete link user profile
        String userName = controller1.userProfileName;

		Test.stopTest();

    }

    static testmethod void test_AddBrandNoRPA () { 

        //Create account, inventory, inventory line items, pricebooks, products, and brands
        Account acc = createAccountWithInventories();

        GT_PriceTrackingClass controller1 = new GT_PriceTrackingClass(new ApexPages.StandardController(acc));
	

        //get the brand IDs to add them to the select list 
        List<Product_Brand__c> lst_PBs = [SELECT Id, Name FROM Product_Brand__c];

        Test.startTest();
        
        PageReference pg=Page.GT_PriceTrackingPage;
        pg.getParameters().put('id',acc.Id);
        
        List<Retail_Price_Archive__c> lst_oldRPAs = [SELECT Id FROM Retail_Price_Archive__c];
        delete lst_oldRPAs;

        Test.setCurrentPage(pg);
        controller1.getRetailPriceArchives();
        
        
        List<Retail_Price_Archive__c> lst_RPAs = [SELECT Id FROM Retail_Price_Archive__c];

        //after the page is loaded and the action is triggered there should be an Retail Price Archive Created 
        system.assertEquals(1, lst_RPAs.size());

        //set the conditions necessary to add a brand - update the list with a checked brand 
        controller1.selectedList = lst_PBs.get(0).Id + ',true,'+ lst_PBs.get(1).Id + ',false,' + lst_PBs.get(2).Id + ',true';

        controller1.addBrand();
        
        //set the wRetailPrice to an arbitraty value so you can save it 
        for(GT_PriceTrackingClass.wRetailPrice wRP : controller1.archivePrices){
            wRP.wrapRP.Price__c = 1;
        }

        //save the brand price 
        controller1.saveChanges();

        //after the brand is added there should be 2 retail prices
        List<Retail_Price__c> lst_RPs = [SELECT Id FROM Retail_Price__c];
        system.assertEquals(2, lst_RPs.size());

		Test.stopTest();

    }

    public static Account createAccountWithInventories(){
        //create test account
        Account acc1 = new Account();
        acc1.name= 'test';
        acc1.Account__c= '123456';
        insert acc1;

        List<Inventory__c> inc_inventories = new List<Inventory__c>();

        //create test inventories on the account 
        //Inventory with todays date
        //Inventory__c inv1= new Inventory__c(Visit_Date__c = Date.Today(), account__c = acc1.Id);
        //insert inv1;
        
        //Inventory without todays date
        Inventory__c inv2= new Inventory__c(Visit_Date__c = Date.Today().addDays(-35), Account__c = acc1.Id);
        inc_inventories.add(inv2);
        insert inv2;

        //create brands and products products
        List<Product2> lst_products = createProducts(acc1);

        //Create inventory with ilis associated to products with assigned brands
        Inventory_Line_Item__c ili1 = new Inventory_Line_Item__c(Account__c=acc1.Id, Inventory__c=inv2.Id, Product__c=lst_products.get(0).Id);
        Inventory_Line_Item__c ili2 = new Inventory_Line_Item__c(Account__c=acc1.Id, Inventory__c=inv2.Id, Product__c=lst_products.get(1).Id);
        Inventory_Line_Item__c ili3 = new Inventory_Line_Item__c(Account__c=acc1.Id, Inventory__c=inv2.Id, Product__c=lst_products.get(2).Id);

        insert ili1;
        insert ili2;
        insert ili3;

        return acc1;
    }

    public static List<Product2> createProducts(Account acc){

        List<Product2> products = new List<Product2>();
        
        //create pricebooks

        Pricebook2 openPB = new Pricebook2(Name = 'Open Stock Items', Description = 'Price Book 2009 Products', IsActive = true); 
        insert openPB;

        Id pricebookId = Test.getStandardPricebookId(); 

        Pricebook2 customPB = new Pricebook2(id=pricebookId, Name='Standard Price Book', isActive=true);
        update customPB;

        //create product brands 
        Product_Brand__c pb1 = new Product_Brand__c(Name='Flat Wrap 2/79');
        Product_Brand__c pb2 = new Product_Brand__c(Name='4KS 60CT');
        Product_Brand__c pb3 = new Product_Brand__c(Name='CITY LIFE 5F99');

        insert pb1;
        insert pb2;
        insert pb3;

        //creat products with associated brands 
        Product2 prod1 = new Product2(Name='Flat Wrap Product', ProductCode='101', Item_Num__c='444441', Item_Status__c='1', Product_Brand__c=pb1.Id, IsActive=true);
        Product2 prod2 = new Product2(Name='4K Lites', ProductCode='102', Item_Num__c='444442', Item_Status__c='1', Product_Brand__c=pb2.Id, IsActive=true);
        Product2 prod3 = new Product2(Name='City Life', ProductCode='103', Item_Num__c='444443', Item_Status__c='1', Product_Brand__c=pb3.Id, IsActive=true);
        
        insert prod1;
        products.add(prod1);

        insert prod2;
        products.add(prod2);
    
        insert prod3;
        products.add(prod3);


        Retail_Price_Archive__c RPA2 = new Retail_Price_Archive__c(Account__c=acc.Id, Recorded_Date__c=date.today().addDays(-40));
        insert RPA2;

        return products;

    }

}