TradeMarketing/force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Great Plains Customer Account Number</description>
    <externalId>true</externalId>
    <inlineHelpText>Great Plains Customer Account Number</inlineHelpText>
    <label>Account #</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

TradeMarketing/force-app/main/default/objects/OrderItem/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>PricebookEntry.Product2.Item_Class_Desc__c</formula>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/OrderItem/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <formula>(PricebookEntry.Product2.Name)</formula>
    <label>Item Description</label>
    <type>Text</type>
</CustomField>

GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End date of the discount, used to calculate recap form quantities.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Starting date of the TMA, used to calculate the recap quantities.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Discount__c</fullName>
        <description>Total discount generated by this agreement.</description>
        <label>Total Discount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Trade Marketing Agreement</label>
    <nameField>
        <label>Trade Marketing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Allowance_Rate__c</fullName>
        <label>Allowance Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Marketing_Agreement__c</fullName>
        <label>Trade Marketing Agreement</label>
        <referenceTo>Trade_Marketing_Agreement__c</referenceTo>
        <relationshipLabel>Trade Marketing Agreement Line Items</relationshipLabel>
        <relationshipName>Trade_Marketing_Agreement_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trade Marketing Agreement Line Item</label>
    <nameField>
        <displayFormat>TMA-{00000000}</displayFormat>
        <label>TMA Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/classes/GT_TMARecapClass.cls
public without sharing class GT_TMARecapClass {
	//001Z000001VAERbIAP
	private final Account acct;
	public  Date startDate{get;set;}
	public  Date endDate{get;set;}
	public String accountId {get; set;}
	public Decimal totalDiscount {get; set;}
	public boolean showResults {get; set;}
	public boolean noResultsFoundMessage {get; set;}

	public List<OrderItem> orderItems {get; set;}
	public List<Trade_Marketing_Agreement_Line_Item__c> tmaLineItems {get; set;}
	public List<TMAWrapperClassObject> tmaWrapList{get; set;}


	public GT_TMARecapClass(ApexPages.StandardController stdController) {
		this.acct = (Account)stdController.getRecord();
	}

	public void DisplayTMARecapFormDataTable(){
		showResults = false;
		noResultsFoundMessage = false;
		getOrderItemsFromAccount();
		getTMADiscountAndAllowanceRate();
		BuildTMARecapFormWithRequiredInformation();
		calculateTotalDiscount();
	}

	private void getOrderItemsFromAccount(){
		accountId = ApexPages.currentPage().getParameters().get('id');
		orderItems = [
				SELECT id, Brand__c, Item_Description__c, Quantity
				FROM OrderItem
				WHERE Order.AccountId = :accountId
		];
	}

	private void getTMADiscountAndAllowanceRate(){
		accountId = ApexPages.currentPage().getParameters().get('id');
		if(startDate != null && endDate != null && startDate <= endDate){
			System.debug('startDate' + startDate);
			System.debug('endDate' + endDate);
			tmaLineItems = [
					SELECT Allowance_Rate__c, Trade_Marketing_Agreement__r.Total_Discount__c
					FROM Trade_Marketing_Agreement_Line_Item__c
					WHERE Trade_Marketing_Agreement__r.Account__c =:accountId
					AND Trade_Marketing_Agreement__r.Start_Date__c =:startDate
					AND Trade_Marketing_Agreement__r.End_Date__c =:endDate
			];
		}
		if(tmaLineItems.size()> 0){
			showResults = true;
			noResultsFoundMessage = false;
		}else{
			showResults = false;
			noResultsFoundMessage = true;
		}
	}


	private void BuildTMARecapFormWithRequiredInformation(){

			tmaWrapList = new List<TMAWrapperClassObject>();
			for(OrderItem order: orderItems)
			{
				for (Trade_Marketing_Agreement_Line_Item__c tmaLineItem : tmaLineItems)
				{
					tmaWrapList.add(new TMAWrapperClassObject
							(
									order.Brand__c,
									order.Item_Description__c,
									order.Quantity,
									tmaLineItem.Trade_Marketing_Agreement__r.Total_Discount__c,
									tmaLineItem.Allowance_Rate__c)
					);
				}

				System.debug('tmaWrapList' + tmaWrapList);
				System.debug('tmaWrapList' + tmaWrapList.size());
			}

	}

	private void calculateTotalDiscount(){
		totalDiscount = 0;
		for(TMAWrapperClassObject TMAWrapperObject: tmaWrapList){
			totalDiscount += TMAWrapperObject.discount;
		}
	}

	public class TMAWrapperClassObject{
		public String brand {get; set;}
		public String brandDescription {get; set;}
		public Decimal quantity {get; set;}
		public Decimal discount {get; set;}
		public Decimal allowanceRate {get; set;}

		public TMAWrapperClassObject(String brand,String brandDescription, Decimal quantity, Decimal discount, Decimal allowanceRate ){
			this.brand = brand;
			this.brandDescription = brandDescription;
			this.quantity = quantity;
			this.discount = discount;
			this.allowanceRate = allowanceRate;
		}
	}
}

/*
todo
throw error message if start date is greater than end date
if two TMA will List update to reflect?
 */