TradeMarketing/force-app/main/default/objects/User/fields/Analyst__c.field-meta.xml
<CustomField>
    <fullName>Analyst__c</fullName>
    <label>Analyst</label>
    <relationshipName>Analyst</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/External_Supervisor_1__c.field-meta.xml
<CustomField>
    <fullName>External_Supervisor_1__c</fullName>
    <description>Email address of user&#39;s supervisor that does not have Salesforce Access.</description>
    <label>External Supervisor 1</label>
    <type>Email</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/External_Supervisor_2__c.field-meta.xml
<CustomField>
    <fullName>External_Supervisor_2__c</fullName>
    <description>Email address of user&#39;s supervisor that does not have Salesforce Access.</description>
    <label>External Supervisor 2</label>
    <type>Email</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/External_Supervisor_3__c.field-meta.xml
<CustomField>
    <fullName>External_Supervisor_3__c</fullName>
    <label>External Supervisor 3</label>
    <type>Email</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/External_Supervisor_4__c.field-meta.xml
<CustomField>
    <fullName>External_Supervisor_4__c</fullName>
    <label>External Supervisor 4</label>
    <type>Email</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/Supervisor_2__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_2__c</fullName>
    <label>Supervisor 2</label>
    <relationshipName>Supervisor2</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/Supervisor_3__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_3__c</fullName>
    <label>Supervisor 3</label>
    <relationshipName>Supervisor3</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/Supervisor_4__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_4__c</fullName>
    <label>Supervisor 4</label>
    <relationshipName>Supervisor4</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

TradeMarketing/force-app/main/default/objects/User/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor 1</label>
    <relationshipName>Supervisor</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

TradeMarketing/mdapi-components/unpackaged/classes/TaskTriggerHandler.cls
public with sharing class TaskTriggerHandler {

    public static void sendEmailOwnerAndCC(List<Task> listTasks){
    	

        User currentUser = [SELECT Id, Analyst__c, Supervisor__c, Supervisor_2__c, Supervisor_3__c, Supervisor_4__c, External_Supervisor_1__c, External_Supervisor_2__c, External_Supervisor_3__c, External_Supervisor_4__c, Name FROM User WHERE Id = : UserInfo.getUserId()];
        List<Messaging.SingleEmailMessage> emailsList = new List<Messaging.SingleEmailMessage>();
    	
        Set<Id> accountIds = new Set<Id>();
        for (Task task : listTasks){
            accountIds.add(task.WhatId);
        }
    	
        Map<Id, Account> accounts = new Map<Id, Account>([SELECT Name, ShippingCity, ShippingState, RecordType.Name FROM Account WHERE Id IN : accountIds]);
        if(!accounts.IsEmpty() && accounts != NULL){
            for (Task task : listTasks){
                String [] ccEmailUsers = new List<String>();

                if (currentUser.Analyst__c != null) {
                    User user1 = [SELECT Email FROM User WHERE Id = :currentUser.Analyst__c];
                    ccEmailUsers.add(''+user1.Email);
                }

                if (currentUser.Supervisor__c!= null) {
                    User user1 = [SELECT Email FROM User WHERE Id = :currentUser.Supervisor__c];
                    ccEmailUsers.add(''+user1.Email);
                }

                if (currentUser.Supervisor_2__c!= null) {
                    User user1 = [SELECT Email FROM User WHERE Id = :currentUser.Supervisor_2__c];
                    ccEmailUsers.add(''+user1.Email);
                }
                
                if (currentUser.Supervisor_3__c != null) {
                    User user1 = [SELECT Email FROM User WHERE Id = :currentUser.Supervisor_3__c];
                    ccEmailUsers.add(''+user1.Email);
                }
                         
                if (currentUser.Supervisor_4__c != null) {
                    User user1 = [SELECT Email FROM User WHERE Id = :currentUser.Supervisor_4__c];
                    ccEmailUsers.add(''+user1.Email);
                }
                
               
                if (currentUser.External_Supervisor_1__c != null) {
                    ccEmailUsers.add(''+currentUser.External_Supervisor_1__c);
                }
                if (currentUser.External_Supervisor_2__c != null) {
                    ccEmailUsers.add(''+currentUser.External_Supervisor_2__c);
                }
                if (currentUser.External_Supervisor_3__c != null) {
                    ccEmailUsers.add(''+currentUser.External_Supervisor_3__c);
                }
                if (currentUser.External_Supervisor_4__c != null) {
                    ccEmailUsers.add(''+currentUser.External_Supervisor_4__c);
                }

                
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();


                mail.setTargetObjectId(currentUser.Id);
                mail.setCcAddresses(ccEmailUsers);
                mail.setSubject(currentUser.Name+ ' - ' +accounts.get(task.WhatId).Name+ ' - '+task.Subject+' - '+Date.today().format());
                //note that styling was added to remove images due to an error in outlook
                mail.setHtmlBody(
                    '<head><style>img{display:none;}</style></head>'+
                    '<b>New task logged by:  </b>' + currentUser.Name + '<br><br>'  +
                    + '<b>Task Type: </b>' + task.Subject + '<br><br>' +
                    + '<b>Account Type: </b>' + accounts.get(task.WhatId).RecordType.Name + '<br><br>' +
                    + '<b>Customer name: </b>' + accounts.get(task.WhatId).Name + '<br><br>' +
                    + '<b>Customer city: </b>' + accounts.get(task.WhatId).ShippingCity + '<br><br>' +
                    + '<b>Customer state: </b>' + accounts.get(task.WhatId).ShippingState + '<br><br>' +
                    + '<b>Purpose of call: </b>' + task.description + '<br><br>' +
                    + '<b>Result: </b>' + task.What_were_your_results__c + '<br><br>' +
                    + '<b>Comments: </b>'+ task.Notes_and_Comments__c + '<br><br>' +
                    + '<b>Comments Continued: </b>'+ task.Notes_and_Comments_Continued__c + '<br><br>'
                    
                );
                mail.saveAsActivity = false;
                emailsList.add(mail);

                //debug
                //System.debug('mail'+mail.getSubject());
            }
            if (emailsList.size() > 0) {
                Messaging.sendEmail(emailsList);
            }
        }
    }
}