GoodTIme_Intelij/src/objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <displayFormat>SFINV-{00000}</displayFormat>
        <label>Inventory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Inventory_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inventory Line Items</relationshipLabel>
        <relationshipName>Inventory_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory</label>
        <referenceTo>Inventory__c</referenceTo>
        <relationshipLabel>Inventory Line Items</relationshipLabel>
        <relationshipName>Inventory_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreviousQuantity__c</fullName>
        <label>Previous Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductDateCode__c</fullName>
        <label>Product Date Code</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>Product2.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Product2.Item_Status__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <filterItems>
                <field>Product2.Item_Status__c</field>
                <operation>equals</operation>
                <value>2</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory Line Items</relationshipLabel>
        <relationshipName>Inventory_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_description__c</fullName>
        <formula>Product__r.Description</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResalePrice__c</fullName>
        <label>Resale Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WholeSaleMargin__c</fullName>
        <formula>IF( (!ISBLANK(ResalePrice__c) &amp;&amp; !ISBLANK(ResalePrice__c)) ,(( ResalePrice__c - WholeSale__c )*100)/ResalePrice__c  ,0)</formula>
        <label>Whole Sale Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WholeSale__c</fullName>
        <label>Whole Sale</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Inventory Line Item</label>
    <nameField>
        <displayFormat>ILI-{000000}</displayFormat>
        <label>Inventory Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/classes/RG_InventoryCloneCls.cls
public class RG_InventoryCloneCls {
        
        public PageReference InventoryClone(){
            id inventoryId=ApexPages.currentPage().getParameters().get('Id');
            
            List<Inventory__c> inventoryList=new List<Inventory__c>();
            Inventory__c inventory;
            try{
                inventory=[SELECT Id, Account__c, Visit_Date__c, Description__c FROM Inventory__c WHERE Id=: inventoryId];
            }Catch(Exception e){
                System.debug('####### No ILI in list ########'+e);
            }
            
            if(inventory!=Null){
            //clone Inventory record
            //
            
            Inventory__c createInventory=inventory.clone(false, true);
            system.debug('createInventory==>'+createInventory);
            
            //Create Inventory record
            try{
                createInventory.Visit_Date__c = Date.today();
                Insert createInventory;
            }Catch(Exception e){
                System.debug('####### createInventory Exception ######## '+e);
            }
            
            List<Inventory_Line_Item__c> inventoryLineItemList=new List<Inventory_Line_Item__c>();
            Map<id, PricebookEntry> Product2IdPriceBookEntryMap=new Map<id, PricebookEntry>();
            for(PricebookEntry pricebookentryy:[SELECT Id, Product2Id, UnitPrice FROM PricebookEntry WHERE Pricebook2.Name='Standard Price Book'])
            {
                if(pricebookentryy.Product2id!=Null)
                Product2IdPriceBookEntryMap.put(pricebookentryy.Product2id, pricebookentryy);
            }
        
            
            for(Inventory_Line_Item__c inventoryLineItem : [SELECT Id, Account__c,PreviousQuantity__c, ProductDateCode__c, WholeSale__c, ResalePrice__c, WholeSaleMargin__c, Inventory__r.Visit_Date__c,  Inventory__c, Product__c, Product_description__c, Quantity__c 
                                                            FROM Inventory_Line_Item__c 
                                                            WHERE Inventory__c=:inventory.Id])
            {
                //clone InventoryLineItem record
                Inventory_Line_Item__c inventLineItem=inventoryLineItem.clone(false, true);
                inventLineItem.Inventory__c=createInventory.Id;
                inventLineItem.Quantity__c=0;
                inventLineItem.PreviousQuantity__c= inventoryLineItem.Quantity__c;
                inventLineItem.ProductDateCode__c=inventoryLineItem.Inventory__r.Visit_Date__c;
                
                if(Product2IdPriceBookEntryMap.get(inventoryLineItem.Product__c)!=NULL)
                    inventLineItem.WholeSale__c=Product2IdPriceBookEntryMap.get(inventoryLineItem.Product__c).UnitPrice;

                inventLineItem.ResalePrice__c=inventoryLineItem.ResalePrice__c;
                
                
                System.debug('inventLineItem===>'+inventLineItem);
                inventoryLineItemList.add(inventLineItem);
            }
            
            
            if(!inventoryLineItemList.isEmpty())
            {
                try{
                    Insert inventoryLineItemList;
                }Catch(Exception e){
                    System.debug('####### inventoryLineItemList Insert Exception ########'+e);
                }
            }
                    
            
            //(SELECT Id, Account__c, Inventory__c, Product__c, Product_description__c, Quantity__c FROM Inventory_Line_Items__r)
            
            return new PageReference('/'+createInventory.Id);
            }
            return new PageReference('/'+inventoryId);
        }
        
}