GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trade Marketing Agreement</label>
    <nameField>
        <label>Trade Marketing Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GoodTIme_Intelij/src/objects/Trade_Marketing_Agreement_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Trade_Marketing_Agreement__c</fullName>
        <label>Trade Marketing Agreement</label>
        <referenceTo>Trade_Marketing_Agreement__c</referenceTo>
        <relationshipLabel>Trade Marketing Agreement Line Items</relationshipLabel>
        <relationshipName>Trade_Marketing_Agreement_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trade Marketing Agreement Line Item</label>
    <nameField>
        <displayFormat>TMA-{00000000}</displayFormat>
        <label>TMA Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Marketing Agreement Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TradeMarketing/force-app/main/default/objects/User/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor 1</label>
    <relationshipName>Supervisor</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

GoodTIme_Intelij/src/classes/GT_TradeMarketingFormController.cls
/**
 *  @author Apical
 *  @date 14 June 2020
 *  @description controller class for Trade Marketing Form component
 */
public class GT_TradeMarketingFormController {
    @AuraEnabled
    public static GT_TradeMarketingFormhelper.BaseResponse getBaseData(String strRecordId) {
        return GT_TradeMarketingFormhelper.getBaseData(strRecordId);
    }

    @AuraEnabled
    public static GT_TradeMarketingFormhelper.ResponseBase saveTradeMarketingAgreement(Trade_Marketing_Agreement__c tradeMarketingAgreement, List<Trade_Marketing_Agreement_Line_Item__c> listLineItems) {
        return GT_TradeMarketingFormhelper.saveTradeMarketingAgreement(tradeMarketingAgreement, listLineItems);
    }

	@AuraEnabled
    public static GT_TradeMarketingFormhelper.ResponseBase approveRecord(String strRecordId, String strApprovalType, String strApproverComment) {
        return GT_TradeMarketingFormhelper.approveRecord(strRecordId, strApprovalType, strApproverComment);
    }

    @AuraEnabled
    public static GT_TradeMarketingFormhelper.LookupData searchPromotions(String strName) {
        return GT_TradeMarketingFormhelper.searchPromotions(strName);
    }

    @AuraEnabled
    public static GT_TradeMarketingFormhelper.ProductBrandList getProductBrands(String strPromotionId) {
        return GT_TradeMarketingFormhelper.getProductBrands(strPromotionId);
    }

    @AuraEnabled
    public static GT_TradeMarketingFormhelper.ResponseBase saveAgreementsListItems(List<Trade_Marketing_Agreement_Line_Item__c> listLineItems) {
        return GT_TradeMarketingFormhelper.saveAgreementsListItems(listLineItems);
    }

    @AuraEnabled
    public static GT_TradeMarketingFormhelper.ResponseBase deleteAgreementsListItem(String strLineItemId) {
        return GT_TradeMarketingFormhelper.deleteAgreementsListItem(strLineItemId);
    }

    @AuraEnabled
    public static GT_TradeMarketingFormhelper.ResponseBase submitForApproval(String strRecordId) {
        return GT_TradeMarketingFormhelper.submitForApproval(strRecordId);
    }


    @AuraEnabled
    public static boolean isValidUser (String userId, String recordId){
        User validUser = [SELECT Id, Email, Supervisor__c, Name  FROM User WHERE Id =:userId];
        Trade_Marketing_Agreement__c TMAccount = [SELECT Id, name, Status__c, Account__c, Account__r.Email__c, Account__r.Name FROM Trade_Marketing_Agreement__c WHERE Id =: recordId LIMIT 1];

        if(validUser.Supervisor__c != null && TMAccount.Account__r.Email__c != null){ return true;}
        else{ return false;}
    }
}